######################################################################################################
#
# If you want to connect to MySQL, you should manually copy MySQL driver to lib directory.
#
######################################################################################################

schemaName: sharding_db

dataSources:
  ds0:
    url: jdbc:mysql://127.0.0.1:3310/ds0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds1:
    url: jdbc:mysql://127.0.0.1:3311/ds1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
 tables:
   t_order:
     actualDataNodes: ds${0..1}.t_order${0..15}
     tableStrategy:
       standard:
         shardingColumn: orderid
         shardingAlgorithmName: t_orderinline
     keyGenerateStrategy:
       column: orderid
       keyGeneratorName: snowflake
 bindingTables:
   - t_order
 defaultDatabaseStrategy:
   standard:
     shardingColumn: userid
     shardingAlgorithmName: database_inline
 defaultTableStrategy:
   none:
 
 shardingAlgorithms:
   database_inline:
     type: INLINE
     props:
       algorithm-expression: ds${userid % 2}
   t_orderinline:
     type: INLINE
     props:
       algorithm-expression: t_order${orderid%10 + 6}
 
 keyGenerators:
   snowflake:
     type: SNOWFLAKE
     